C_L, C_D0 = 0, 0        # Lift and profile drag coefficients
D, L = 0, 0             # Drag and lift force
f, f_0 = 0, 0           # Glide slope function and sink rate function
g_l, g_u = 0, 0         # Optimal velocity Lower and upper bounds auxiliary functions
K = 0                   # Induced drag coefficient
m = 0                   # Aircraft’s mass
n, n_max = 0, 0         # Load factor and maximal load factor
q, q_0 = 0, 0           # Dynamic pressure, optimal dynamic pressure in still air
S = 0                   # Aerodynamic surface
V_MS = 0                # Minimum sink rate glide velocity
V_stall, V_max = 0, 0   # Aircraft’s stall and maximum velocity
Psi, Psi_max = 0, 0     # The bank angle, maximal bank angle
Ro = 0                  # Air-density
g = 9.80665             # Gravitational force